language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-api-frontend
  - docker build -t reverseproxy ./reverseproxy
  - docker tag udagram-api-feed kinggeorge1/udagram-api-feed:v1
  - docker tag udagram-api-user kinggeorge1/udagram-api-user:v1
  - docker tag udagram-frontend kinggeorge1/udagram-frontend:v1
  - docker tag reverseproxy kinggeorge1/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kinggeorge1/udagram-api-feed:v1
  - docker push kinggeorge1/udagram-api-user:v1
  - docker push kinggeorge1/udagram-frontend:v1
  - docker push kinggeorge1/reverseproxy:v1
